export const courses = [
  {
    title: 'Go Anon Board',
    slug: 'go-anon-board',
    pid: 'PLBeQxJQNprbjDQ4fJi58jOcZYA8VYauVh',
    lastUpdated: '2021-03-31T14:00:33.000Z',
    description: '',
    image: 'go-anon-board.jpg',
    tags: ['golang', 'postgres'],
    videos: [
      {
        ordinance: 0,
        videoId: 'V3T5d1TZ3wA',
        title: 'Go Anon Board [1] - Production Ready Set Up',
        publishedAt: '2021-03-09T15:00:12Z',
      },
      {
        ordinance: 1,
        videoId: '5kYYnXuPwek',
        title: 'Go Anon Board [2] - GORM Database Connection',
        publishedAt: '2021-03-11T15:00:05Z',
      },
      {
        ordinance: 2,
        videoId: 'eJNlz3c_yPU',
        title: 'Go Anon Board [3] - Business Logic',
        publishedAt: '2021-03-17T14:00:28Z',
      },
      {
        ordinance: 3,
        videoId: 'N-w9yok22W4',
        title: 'Go Anon Board [4] - Feature Complete',
        publishedAt: '2021-03-24T14:00:06Z',
      },
    ],
  },
  {
    title: 'NextJS Jobs Listings',
    slug: 'nextjs-jobs-listings',
    pid: 'PLBeQxJQNprbhUU5hrPlENx4V3jVhDK2_F',
    lastUpdated: '2021-02-16T15:00:11.000Z',
    description: '',
    image: 'next-jobs.png',
    tags: ['NextJS', 'react', 'typescirpt'],
    videos: [
      {
        ordinance: 0,
        videoId: '-nDGZK9sbYI',
        title: 'NextJS Job Listings [1] - Project Setup',
        publishedAt: '2021-02-02T17:00:01Z',
      },
      {
        ordinance: 1,
        videoId: '1eFHGrJarEQ',
        title: 'NextJS Job Listings [2] - Card UI',
        publishedAt: '2021-02-04T17:00:01Z',
      },
      {
        ordinance: 2,
        videoId: 'g8gpi-6x8ro',
        title: 'NextJS Job Listings [3] - Job Page',
        publishedAt: '2021-02-09T15:00:16Z',
      },
      {
        ordinance: 3,
        videoId: 'Z4fPxqH38MQ',
        title: 'NextJS Job Listings [4] - Search Widgets',
        publishedAt: '2021-02-11T15:00:11Z',
      },
      {
        ordinance: 4,
        videoId: 'bA3zLZK4Ay8',
        title: 'NextJS Job Listings [5] - Pagination and Deployment',
        publishedAt: '2021-02-16T15:00:11Z',
      },
    ],
  },
  {
    title: 'Nx Space Explorer',
    slug: 'nx-space-explorer',
    pid: 'PLBeQxJQNprbjZmm6JG_mrnqAVr9zIjbxc',
    lastUpdated: '2021-01-12T17:00:12.000Z',
    description: '',
    image: 'nx-space-explorer.png',
    tags: [
      'nestjs',
      'typescript',
      'nextjs',
      'react',
      'nx',
      'docker',
      'postgres',
    ],
    videos: [
      {
        ordinance: 0,
        videoId: 'kcCiOAjQxAU',
        title: 'Nx Space Explorer [1] - Reinitializing Project',
        publishedAt: '2020-12-14T17:00:15Z',
      },
      {
        ordinance: 1,
        videoId: 'cvuZvpRn91Y',
        title: 'Nx Space Explorer [2] - NestJS Launch Module',
        publishedAt: '2020-12-15T17:00:13Z',
      },
      {
        ordinance: 2,
        videoId: 'oKcjABQVVmg',
        title: 'Nx Space Explorer [3] - NestJS User Module',
        publishedAt: '2020-12-22T16:00:27Z',
      },
      {
        ordinance: 3,
        videoId: 'tsPij-TjKw4',
        title: 'Nx Space Explorer [4] - Setting up NextJS and GraphQL Codegen',
        publishedAt: '2020-12-28T16:00:09Z',
      },
      {
        ordinance: 4,
        videoId: 'cdpI8o05kn8',
        title: 'Nx Space Explorer [5] - NextJS Launches',
        publishedAt: '2020-12-28T17:00:11Z',
      },
      {
        ordinance: 5,
        videoId: 'yQ0Nm6lKHNY',
        title: 'Nx Space Explorer [6] - SSR and Infinite Scroll',
        publishedAt: '2021-01-05T17:00:34Z',
      },
      {
        ordinance: 6,
        videoId: 'sy1PdnrjhQA',
        title: 'Nx Space Explorer [7] - Client Side Authentication',
        publishedAt: '2021-01-07T17:00:16Z',
      },
      {
        ordinance: 7,
        videoId: 'Y_botHhHpdg',
        title: 'Nx Space Explorer [8] - Cart State Management',
        publishedAt: '2021-01-12T17:00:12Z',
      },
    ],
  },
  {
    title: 'Clojure Auth',
    slug: 'clojure-auth',
    pid: 'PLBeQxJQNprbjvILPGCw4h7pFOZp_Yms1B',
    lastUpdated: '2020-11-30T17:00:07Z',
    description: '',
    image: 'clj-auth.jpg',
    tags: ['clojure'],
    videos: [
      {
        ordinance: 0,
        videoId: 'TQ0xIPI-8Z0',
        title: '[Clojure Auth][1] Reviewing Reitit and Ring',
        publishedAt: '2020-11-20T17:00:08Z',
      },
      {
        ordinance: 1,
        videoId: 'OGj5S0H4hPg',
        title: '[Clojure Auth][2] Honeysql and next.jdbc',
        publishedAt: '2020-11-23T17:00:14Z',
      },
      {
        ordinance: 2,
        videoId: 'FcxO5VCPLi4',
        title: '[Clojure Auth][3] Signed JWT authentication with Buddy',
        publishedAt: '2020-11-30T17:00:07Z',
      },
    ],
  },
  {
    title: 'Full Stack Clojure Contact Book',
    slug: 'full-stack-clojure-contact-book',
    pid: 'PLBeQxJQNprbgkmvbv80xC8R0SHcPsosjZ',
    lastUpdated: '2020-08-03T16:00:15.000Z',
    description: '',
    image: 'fullstack-clj.png',
    tags: ['clojure'],
    videos: [
      {
        ordinance: 2,
        videoId: 'R5YZRfABbWY',
        title: 'Full Stack Clojure Contact Book - [1] Reitit Ring Set Up',
        publishedAt: '2020-07-13T07:00:04Z',
      },
      {
        ordinance: 3,
        videoId: '2_Pd6QeFqYs',
        title: 'Full Stack Clojure Contact Book - [2] HugSQL Configuration',
        publishedAt: '2020-07-15T07:00:00Z',
      },
      {
        ordinance: 4,
        videoId: 'dMB-EWpR_Cw',
        title: 'Full Stack Clojure Contact Book - [3] API Endpoints',
        publishedAt: '2020-07-17T07:00:16Z',
      },
      {
        ordinance: 5,
        videoId: 'Jf94HNmCXyU',
        title: 'Full Stack Clojure Contact Book - [4] Front End Preparation',
        publishedAt: '2020-07-20T07:00:03Z',
      },
      {
        ordinance: 6,
        videoId: 'PDtv-CL0XeI',
        title: 'Full Stack Clojure Contact Book - [5] React Components',
        publishedAt: '2020-07-27T16:00:12Z',
      },
      {
        ordinance: 7,
        videoId: 'PRDP5ba8lPU',
        title: 'Full Stack Clojure Contact Book - [6] State Management',
        publishedAt: '2020-07-31T16:00:07Z',
      },
      {
        ordinance: 8,
        videoId: 'p8d9VtrdZ7Y',
        title: 'Full Stack Clojure Contact Book - [7] Final Integration',
        publishedAt: '2020-08-03T16:00:15Z',
      },
    ],
  },
  {
    title: 'Angular Countries',
    slug: 'angular-countries',
    pid: 'PLBeQxJQNprbhUlUVzLimbu2NS3iCxnPi_',
    lastUpdated: '2020-06-22T07:00:03Z',
    description:
      'In this video series, take on the frontend mentor challenge to do the countries REST api application with Angular.',
    image: 'angular-countries.png',
    tags: ['Angular', 'RxJS'],
    videos: [
      {
        ordinance: 0,
        videoId: '4nMpvb12Uo8',
        title: 'Angular Countries - [1] Setup and Theming',
        publishedAt: '2020-06-17T07:00:02Z',
      },
      {
        ordinance: 1,
        videoId: 'YkVShyTILpY',
        title: 'Angular Countries - [2] Api Service',
        publishedAt: '2020-06-19T07:00:16Z',
      },
      {
        ordinance: 2,
        videoId: 'hXXwm0QRTEU',
        title: 'Angular Countries - [3] Page Styling',
        publishedAt: '2020-06-20T07:00:12Z',
      },
      {
        ordinance: 3,
        videoId: '4ekenSY6jac',
        title: 'Angular Countries - [4] Filter Options',
        publishedAt: '2020-06-22T07:00:03Z',
      },
    ],
  },
  {
    title: 'React Conduit',
    slug: 'react-conduit',
    pid: 'PLBeQxJQNprbhO7-QgNP2JLicOyUuNdy5T',
    lastUpdated: '2020-04-10T07:00:02.000Z',
    description:
      'Learn a different React stack, this frontend framework uses Overmind for state management and @reach/router for navigation.',
    image: 'react-conduit.jpg',
    tags: ['React', 'Overmind', 'reach router', 'Bootstrap', 'Typescript'],
    videos: [
      {
        ordinance: 0,
        videoId: 'ECZTGnFaHm4',
        title: 'React Conduit - Introduction',
        publishedAt: '2020-03-31T12:10:04.000Z',
      },
      {
        ordinance: 1,
        videoId: 'lq-69Y9IKTM',
        title: 'React Conduit - [1] Setup Reach Router and Overmind JS',
        publishedAt: '2020-03-31T12:34:08.000Z',
      },
      {
        ordinance: 2,
        videoId: 'QTNbgQu8844',
        title: 'React Conduit - [2] Authentication State in OvermindJS',
        publishedAt: '2020-04-04T15:00:10.000Z',
      },
      {
        ordinance: 3,
        videoId: 'n-PWPqFnbq8',
        title: 'React Conduit - [3] Authentication Form with Formik',
        publishedAt: '2020-04-05T12:00:33.000Z',
      },
      {
        ordinance: 4,
        videoId: 'p407XPG66kk',
        title: 'React Conduit - [4] User Settings and Profiles',
        publishedAt: '2020-04-06T12:00:34.000Z',
      },
      {
        ordinance: 5,
        videoId: 'alPwzUIVZoc',
        title: 'React Conduit - [5] User Settings and Profile part 2',
        publishedAt: '2020-04-08T07:00:00.000Z',
      },
      {
        ordinance: 6,
        videoId: 'D2Fo61g0RWU',
        title: 'React Conduit - [6] Article Listings',
        publishedAt: '2020-04-10T07:00:02.000Z',
      },
      {
        ordinance: 7,
        videoId: 'zl4oEmtcJA0',
        title: 'React Conduit - [7] Article Optimizations',
        publishedAt: '2020-04-14T16:51:29.000Z',
      },
      {
        ordinance: 8,
        videoId: 'q4d9UxxcVpM',
        title: 'React Conduit - [8] Articles User Interface',
        publishedAt: '2020-04-17T07:00:30.000Z',
      },
      {
        ordinance: 9,
        videoId: 'yIzrEAickfQ',
        title: 'React Conduit - [9] Article Page',
        publishedAt: '2020-04-18T07:00:30.000Z',
      },
      {
        ordinance: 10,
        videoId: 'BRYjX0O8-m4',
        title: 'React Conduit - [10] Editor Page',
        publishedAt: '2020-04-23T07:00:02.000Z',
      },
      {
        ordinance: 11,
        videoId: '1SMqLtKXloQ',
        title: 'React Conduit - [11] Adding Comments',
        publishedAt: '2020-04-25T07:00:01.000Z',
      },
    ],
  },
  {
    title: 'NestJS Blog API',
    slug: 'NestJS-Blog-API',
    pid: 'PLBeQxJQNprbjZL5iguWelcxlmWvY4Dmdj',
    lastUpdated: '2020-03-26T15:00:38.000Z',
    description:
      "Learn to create a medium clone Rest API with NestJS and PostgreSQL with the help of TypeORM. This application is based on go thinkster's Real World App repository.",
    image: 'nestjs-blog-api.jpg',
    tags: ['NestJS', 'PostgreSQL', 'rest api', 'TypeScript'],
    videos: [
      {
        ordinance: 0,
        videoId: 'AZfa-AFwjgo',
        title: 'NestJS Blog API - [1] Database Connection',
        publishedAt: '2020-03-19T15:00:01.000Z',
      },
      {
        ordinance: 1,
        videoId: 'kMXp20gn-ms',
        title: 'NestJS Blog API - [0] Introduction',
        publishedAt: '2020-03-19T15:00:32.000Z',
      },
      {
        ordinance: 2,
        videoId: 'DreKPQNBCYc',
        title: 'NestJS Blog API - [2] Begin Auth Module',
        publishedAt: '2020-03-20T15:00:11.000Z',
      },
      {
        ordinance: 3,
        videoId: 'EZxkEr8-cW8',
        title: 'NestJS Blog API - [3] User Entity',
        publishedAt: '2020-03-21T15:00:07.000Z',
      },
      {
        ordinance: 4,
        videoId: 'B6deaSUgkHc',
        title: 'NestJS Blog API - [4] Authentication',
        publishedAt: '2020-03-22T15:00:04.000Z',
      },
      {
        ordinance: 5,
        videoId: 'PAFR7DpUBEY',
        title: 'NestJS Blog API - [5] User Module',
        publishedAt: '2020-03-22T15:15:00.000Z',
      },
      {
        ordinance: 6,
        videoId: 'yReDGmdFQ0A',
        title: 'NestJS Blog API - [6] User Profile',
        publishedAt: '2020-03-22T16:00:19.000Z',
      },
      {
        ordinance: 7,
        videoId: '00MeclezvlA',
        title: 'NestJS Blog API - [7] e2e Testing with Postman',
        publishedAt: '2020-03-23T15:00:00.000Z',
      },
      {
        ordinance: 8,
        videoId: 'yHdrQlF62Zc',
        title: 'NestJS Blog API - [8] Article Entity',
        publishedAt: '2020-03-24T15:00:23.000Z',
      },
      {
        ordinance: 9,
        videoId: '-maNVWh4_eA',
        title: 'NestJS Blog API - [9] Article CRUD',
        publishedAt: '2020-03-24T15:15:00.000Z',
      },
      {
        ordinance: 10,
        videoId: 'tLzOvoVr7Qg',
        title: 'NestJS Blog API - [10] Find Article',
        publishedAt: '2020-03-24T16:00:17.000Z',
      },
      {
        ordinance: 11,
        videoId: 'lYrykF2Uqvk',
        title: 'NestJS Blog API - [11] Comment Module',
        publishedAt: '2020-03-25T15:00:30.000Z',
      },
      {
        ordinance: 12,
        videoId: 'dl9srgihNAY',
        title: 'NestJS Blog API - [12] Refactor',
        publishedAt: '2020-03-25T15:30:02.000Z',
      },
      {
        ordinance: 13,
        videoId: 'r0TP4DdXeIk',
        title: 'Swagger in NestJS',
        publishedAt: '2020-03-26T15:00:38.000Z',
      },
    ],
  },
  {
    title: 'Redux Tip Calculator',
    slug: 'redux-tip-calculator',
    pid: 'PLBeQxJQNprbgAeAi15SWDS8Is28HxazqV',
    lastUpdated: '2020-01-20T08:00:01.000Z',
    description:
      'Learn how to integrate the Redux state management library with a Typescript React project.',
    image: 'redux-tip.jpg',
    tags: ['React', 'Redux', 'TypeScript'],
    videos: [
      {
        ordinance: 0,
        videoId: 'zq-HRXtj2TI',
        title: 'Redux Tip Calculator [Introduction]',
        publishedAt: '2020-01-15T08:00:14.000Z',
        thumbnail: 'https://i.ytimg.com/vi/zq-HRXtj2TI/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'l2Cj3yo7W4E',
        title: 'Redux Tip Calculator [1] Create Store',
        publishedAt: '2020-01-15T08:00:15.000Z',
        thumbnail: 'https://i.ytimg.com/vi/l2Cj3yo7W4E/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'PATxpvzcJmg',
        title: 'Redux Tip Calculator [2] Actions and Reducers',
        publishedAt: '2020-01-16T08:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/PATxpvzcJmg/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'sbzbOXorg60',
        title: 'Redux Tip Calculator [3] MVP',
        publishedAt: '2020-01-17T08:00:11.000Z',
        thumbnail: 'https://i.ytimg.com/vi/sbzbOXorg60/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'm12trZiVoMY',
        title: 'Redux Tip Calculator [4] Styling with TailwindCSS',
        publishedAt: '2020-01-18T08:00:08.000Z',
        thumbnail: 'https://i.ytimg.com/vi/m12trZiVoMY/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: 'Fq0tlyFatGw',
        title: 'Redux Tip Calculator [5] Testing with Jest',
        publishedAt: '2020-01-19T08:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/Fq0tlyFatGw/maxresdefault.jpg',
      },
      {
        ordinance: 6,
        videoId: '1n8IY12ROrg',
        title: 'Redux Tip Calculator [6] Bug Fixes',
        publishedAt: '2020-01-20T08:00:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/1n8IY12ROrg/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Scala Mongo API',
    slug: 'scala-mongo-api',
    pid: 'PLBeQxJQNprbhb6kOJS477I_laHQTGgjg8',
    lastUpdated: '2019-06-22T16:00:05.000Z',
    description:
      'Learn how to create a simple Rest API with the Play framework in Scala and use MongoDB as the data layer.',
    image: 'scala-mongo.jpg',
    tags: ['Scala', 'rest api', 'MongoDB', 'play framework'],
    videos: [
      {
        ordinance: 0,
        videoId: 'XD_X3BMsRhg',
        title: 'Scala Mongo API [1] - Data Model',
        publishedAt: '2019-06-20T16:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/XD_X3BMsRhg/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: '_C5IlQgJbTo',
        title: 'Scala Mongo API [2] - Service Layer',
        publishedAt: '2019-06-21T16:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/_C5IlQgJbTo/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'G6But_7ug9Q',
        title: 'Scala Mongo API [3] - API Controller',
        publishedAt: '2019-06-22T16:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/G6But_7ug9Q/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'NestJS ECommerce',
    slug: 'nestjs-ecommerce',
    pid: 'PLBeQxJQNprbiykCyVNcSExTgytMMjSjnQ',
    lastUpdated: '2019-04-02T16:00:01.000Z',
    description:
      'Learn how to create an e-commerce server architecture Rest API in NestJS with MongoDB as the database.',
    image: 'nestjs-commerce.jpg',
    tags: ['MongoDB', 'NestJS'],
    videos: [
      {
        ordinance: 0,
        videoId: '-8Q62rTswSQ',
        title: 'NestJS ECommerce - [0] Introduction',
        publishedAt: '2019-02-15T19:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/-8Q62rTswSQ/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'PPCuBln5FyE',
        title: 'NestJS ECommerce - [1] Environment Set Up',
        publishedAt: '2019-02-16T19:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/PPCuBln5FyE/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'hcKTQS9RxA0',
        title: 'NestJS ECommerce - [2] Models',
        publishedAt: '2019-02-17T18:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/hcKTQS9RxA0/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 's33_LCPrrGc',
        title: 'NestJS ECommerce - [3] Shared User Service',
        publishedAt: '2019-02-22T18:00:06.000Z',
        thumbnail: 'https://i.ytimg.com/vi/s33_LCPrrGc/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'BR0CaqiHco4',
        title: 'NestJS ECommerce - [4] Passport Authentication',
        publishedAt: '2019-02-23T18:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/BR0CaqiHco4/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: 'D7bCHaiSTNY',
        title: 'NestJS ECommerce - [5] End To End Testing',
        publishedAt: '2019-02-24T18:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/D7bCHaiSTNY/maxresdefault.jpg',
      },
      {
        ordinance: 6,
        videoId: 'SL-VQcBCQIM',
        title: 'NestJS ECommerce - [6] Authorization',
        publishedAt: '2019-02-27T18:00:07.000Z',
        thumbnail: 'https://i.ytimg.com/vi/SL-VQcBCQIM/maxresdefault.jpg',
      },
      {
        ordinance: 7,
        videoId: 'MYGghqyGLOU',
        title: 'NestJS ECommerce - [7] Testing Improvements',
        publishedAt: '2019-02-28T18:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/MYGghqyGLOU/maxresdefault.jpg',
      },
      {
        ordinance: 8,
        videoId: 'cN8xKSWcepo',
        title: 'NestJS ECommerce - [8] Product Listings',
        publishedAt: '2019-03-03T18:00:04.000Z',
        thumbnail: 'https://i.ytimg.com/vi/cN8xKSWcepo/maxresdefault.jpg',
      },
      {
        ordinance: 9,
        videoId: 'yu0-PjfVdTA',
        title: 'NestJS ECommerce - [9] Product Testing',
        publishedAt: '2019-03-04T18:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/yu0-PjfVdTA/maxresdefault.jpg',
      },
      {
        ordinance: 10,
        videoId: 'uB3NBbXa_MU',
        title: 'NestJS ECommerce - [10] Test Driven Development',
        publishedAt: '2019-03-12T17:00:10.000Z',
        thumbnail: 'https://i.ytimg.com/vi/uB3NBbXa_MU/maxresdefault.jpg',
      },
      {
        ordinance: 11,
        videoId: 'CCKsE2_84Cc',
        title: 'NestJS ECommerce - [11] TDD Order Service',
        publishedAt: '2019-03-30T16:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/CCKsE2_84Cc/maxresdefault.jpg',
      },
      {
        ordinance: 12,
        videoId: '0CfuBokD_xA',
        title: 'NestJS ECommerce - [12] Google Cloud Deployment',
        publishedAt: '2019-04-02T16:00:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/0CfuBokD_xA/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Ideas App - Angular NgRx',
    slug: 'ideas-app-angular-ngrx',
    pid: 'PLBeQxJQNprbiJm55q7nTAfhMmzIC8MWxc',
    lastUpdated: '2018-12-16T21:44:37.000Z',
    description:
      'Learn Angular and NgRx state management by creating the front end of the Ideas app, which is a reddit-like application for managing ideas.',
    image: 'angular-ideas.jpg',
    tags: ['Angular', 'NgRx', 'RxJS'],
    videos: [
      {
        ordinance: 0,
        videoId: 'wR8IslNgtG0',
        title: 'Ideas App - Angular NgRx 01 Introduction',
        publishedAt: '2018-10-27T23:50:37.000Z',
        thumbnail: 'https://i.ytimg.com/vi/wR8IslNgtG0/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'CP6y5L21DIQ',
        title: 'Ideas App - Angular NgRx 02 Services',
        publishedAt: '2018-10-28T19:12:16.000Z',
        thumbnail: 'https://i.ytimg.com/vi/CP6y5L21DIQ/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'wvAiaepEBj4',
        title: 'Ideas App - Angular NgRx 03 Actions and Reducers',
        publishedAt: '2018-10-29T19:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/wvAiaepEBj4/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'pZBVRYT4oSc',
        title: 'Ideas App - Angular NgRx 04 Effects',
        publishedAt: '2018-10-30T18:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/pZBVRYT4oSc/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'DjS6SFBLPb4',
        title: 'Ideas App - Angular NgRx 05 Dispatching Authentication',
        publishedAt: '2018-11-01T18:30:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/DjS6SFBLPb4/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: '_c37v6IVWz4',
        title: 'Ideas App - Angular NgRx 06 Reactive Forms',
        publishedAt: '2018-11-02T21:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/_c37v6IVWz4/maxresdefault.jpg',
      },
      {
        ordinance: 6,
        videoId: 'Z3qwb5ZovKg',
        title: 'Ideas App - Angular NgRx 07 Error Toast',
        publishedAt: '2018-11-21T00:19:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/Z3qwb5ZovKg/maxresdefault.jpg',
      },
      {
        ordinance: 7,
        videoId: 'SENW0O6ggo8',
        title: 'Ideas App - Angular NgRx 08 Router Store',
        publishedAt: '2018-11-21T19:41:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/SENW0O6ggo8/maxresdefault.jpg',
      },
      {
        ordinance: 8,
        videoId: '0kSU1e5LK08',
        title: 'Ideas App - Angular NgRx 09 User Feature Module',
        publishedAt: '2018-11-25T19:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/0kSU1e5LK08/maxresdefault.jpg',
      },
      {
        ordinance: 9,
        videoId: 'zs3IN3FYjoM',
        title: 'Ideas App - Angular NgRx 10 Entity and Selectors',
        publishedAt: '2018-12-05T20:00:12.000Z',
        thumbnail: 'https://i.ytimg.com/vi/zs3IN3FYjoM/maxresdefault.jpg',
      },
      {
        ordinance: 10,
        videoId: 'JYbHDfJNYhw',
        title: 'Ideas App - Angular NgRx 11 CRUD Operations',
        publishedAt: '2018-12-09T19:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/JYbHDfJNYhw/maxresdefault.jpg',
      },
      {
        ordinance: 11,
        videoId: 'PEh7BqexJOI',
        title: 'Ideas App - Angular NgRx 12 Selected Idea',
        publishedAt: '2018-12-10T19:30:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/PEh7BqexJOI/maxresdefault.jpg',
      },
      {
        ordinance: 12,
        videoId: 'rLe1cGBFbNI',
        title: 'Ideas App - Angular NgRx 13 Conclusion',
        publishedAt: '2018-12-16T21:44:37.000Z',
        thumbnail: 'https://i.ytimg.com/vi/rLe1cGBFbNI/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Ideas App - NestJS GraphQL',
    slug: 'ideas-app-nestjs-graphql',
    pid: 'PLBeQxJQNprbiJm55q7nTAfhMmzIC8MWxc',
    lastUpdated: '2018-10-22T18:30:00.000Z',
    description: 'Add a GraphQL layer to the Ideas app',
    image: 'nestjs-ideas-graphql.jpg',
    tags: ['NestJS', 'TypeScript', 'GraphQL'],
    videos: [
      {
        ordinance: 0,
        videoId: 'lIOMUCdA4Zs',
        title: 'Ideas App - NestJS GraphQL 01 Integration',
        publishedAt: '2018-10-14T15:48:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/lIOMUCdA4Zs/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'EMuDORCLxDs',
        title: 'Ideas App - NestJS GraphQL 02 Queries',
        publishedAt: '2018-10-15T18:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/EMuDORCLxDs/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'C261knBYRyk',
        title: 'Ideas App - NestJS GraphQL 03 User Resolver',
        publishedAt: '2018-10-16T18:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/C261knBYRyk/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'VSyHNRbzKXM',
        title: 'Ideas App - NestJS GraphQL 04 Comment Mutations',
        publishedAt: '2018-10-21T18:00:03.000Z',
        thumbnail: 'https://i.ytimg.com/vi/VSyHNRbzKXM/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'opYgfyQnKwE',
        title: 'Ideas App - NestJS GraphQL 05 Idea Resolver',
        publishedAt: '2018-10-22T18:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/opYgfyQnKwE/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Ideas App - NestJS API',
    slug: 'ideas-app-nestjs-api',
    pid: 'PLBeQxJQNprbiJm55q7nTAfhMmzIC8MWxc',
    lastUpdated: '2018-10-11T18:30:00.000Z',
    description:
      'Learn NestJS by creating a Rest API with PostgreSQL as the database and TypeORM to interact with it. This is the beginning of a full stack application similar to reddit and twitter that will manage ideas.',
    image: 'nestjs-ideas.jpg',
    tags: ['NestJS', 'PostgreSQL', 'TypeScript', 'rest api'],
    videos: [
      {
        ordinance: 0,
        videoId: 'NF9Xn4g5MJY',
        title: 'Ideas App - NestJS API 01 Introduction',
        publishedAt: '2018-09-14T23:08:51.000Z',
        thumbnail: 'https://i.ytimg.com/vi/NF9Xn4g5MJY/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'EHlhvy-fh90',
        title: 'Ideas App - NestJS API 02 Database Connection',
        publishedAt: '2018-09-15T20:34:48.000Z',
        thumbnail: 'https://i.ytimg.com/vi/EHlhvy-fh90/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'T4YnLTtIMw4',
        title: 'Ideas App - NestJS API 03 CRUD Operations',
        publishedAt: '2018-09-16T17:44:07.000Z',
        thumbnail: 'https://i.ytimg.com/vi/T4YnLTtIMw4/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'XP_gONOksuM',
        title: 'Ideas App - NestJS API 04 Errors and Logging',
        publishedAt: '2018-09-18T18:00:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/XP_gONOksuM/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'LQWwVDh3Vx4',
        title: 'Ideas App - NestJS API 05 Validation Errors',
        publishedAt: '2018-09-22T02:10:51.000Z',
        thumbnail: 'https://i.ytimg.com/vi/LQWwVDh3Vx4/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: 'gCK8BZyNaos',
        title: 'Ideas App - NestJS API 06 Users Module',
        publishedAt: '2018-09-25T18:00:03.000Z',
        thumbnail: 'https://i.ytimg.com/vi/gCK8BZyNaos/maxresdefault.jpg',
      },
      {
        ordinance: 6,
        videoId: 'rDEWj3aK5hI',
        title: 'Ideas App - NestJS API 07 Authentication',
        publishedAt: '2018-09-27T18:30:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/rDEWj3aK5hI/maxresdefault.jpg',
      },
      {
        ordinance: 7,
        videoId: '4GC8z0EfV6g',
        title: 'Ideas App - NestJS API 08 Relationships',
        publishedAt: '2018-09-29T19:45:08.000Z',
        thumbnail: 'https://i.ytimg.com/vi/4GC8z0EfV6g/maxresdefault.jpg',
      },
      {
        ordinance: 8,
        videoId: 'q7uvzk9PWLw',
        title: 'Ideas App - NestJS 09 API Junction Tables',
        publishedAt: '2018-10-02T18:00:05.000Z',
        thumbnail: 'https://i.ytimg.com/vi/q7uvzk9PWLw/maxresdefault.jpg',
      },
      {
        ordinance: 9,
        videoId: 'MYFaIVj4GbA',
        title: 'Ideas App - NestJS API 10 Comments Module',
        publishedAt: '2018-10-07T00:07:54.000Z',
        thumbnail: 'https://i.ytimg.com/vi/MYFaIVj4GbA/maxresdefault.jpg',
      },
      {
        ordinance: 10,
        videoId: 'zZZ4w-RCszQ',
        title: 'Ideas App - NestJS API 11 Fake Data',
        publishedAt: '2018-10-10T18:30:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/zZZ4w-RCszQ/maxresdefault.jpg',
      },
      {
        ordinance: 11,
        videoId: 'p8sKVKMJRco',
        title: 'Ideas App - NestJS API 12 Pagination',
        publishedAt: '2018-10-11T18:30:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/p8sKVKMJRco/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Angular Simon Game',
    slug: 'angular-simon-game',
    pid: 'PLBeQxJQNprbgZgivXyBX-djYAhMJGE93B',
    lastUpdated: '2018-08-28T18:17:12.000Z',
    description: 'Learn Angular by creating a simon says game.',
    image: 'angular-simon.jpg',
    tags: ['Angular'],
    videos: [
      {
        ordinance: 0,
        videoId: 'n03enYvqlN4',
        title: 'Angular Simon Game - 01 Introduction',
        publishedAt: '2018-08-20T01:19:03.000Z',
        thumbnail: 'https://i.ytimg.com/vi/n03enYvqlN4/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'kaIHOSxBN2w',
        title: 'Angular Simon Game - 02 Components',
        publishedAt: '2018-08-20T19:30:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/kaIHOSxBN2w/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'zCRWi7_uP2I',
        title: 'Angular Simon Game - 03 Game State',
        publishedAt: '2018-08-22T19:30:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/zCRWi7_uP2I/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'nUKGaMuKTEo',
        title: 'Angular Simon Game - 04 Set State',
        publishedAt: '2018-08-25T18:31:10.000Z',
        thumbnail: 'https://i.ytimg.com/vi/nUKGaMuKTEo/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'GRhn5oBzCEQ',
        title: 'Angular Simon Game - 05 Styling',
        publishedAt: '2018-08-26T18:30:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/GRhn5oBzCEQ/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: 'k8qpbqgIcMk',
        title: 'Angular Simon Game - 06 Tease Player',
        publishedAt: '2018-08-28T18:17:12.000Z',
        thumbnail: 'https://i.ytimg.com/vi/k8qpbqgIcMk/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'TypeScript Gropceries API',
    slug: 'typescript-gropceries-api',
    pid: 'PLBeQxJQNprbhvbBAmoyIJykggzE_JIhWe',
    lastUpdated: '2018-07-17T23:29:01.000Z',
    description:
      'Learn Typescript by creating a node.js express server that manages groceries lists.',
    image: 'ts-groceries.jpg',
    tags: ['TypeScript', 'PostgreSQL', 'rest api'],
    videos: [
      {
        ordinance: 0,
        videoId: 'rKIy0rlzqsU',
        title: 'TypeScript Groceries API - 01 Intro and Set up',
        publishedAt: '2018-07-12T23:18:48.000Z',
        thumbnail: 'https://i.ytimg.com/vi/rKIy0rlzqsU/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: 'I8pqxI7GDs0',
        title: 'TypeScript Groceries API - 02 Database Connection',
        publishedAt: '2018-07-14T00:59:24.000Z',
        thumbnail: 'https://i.ytimg.com/vi/I8pqxI7GDs0/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'FPSYjuvh6d4',
        title: 'TypeScript Groceries API - 03 Setting up grocery routes',
        publishedAt: '2018-07-15T05:16:41.000Z',
        thumbnail: 'https://i.ytimg.com/vi/FPSYjuvh6d4/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: '7JejrBPr0iM',
        title: 'TypeScript Groceries API - 04 Groceries CRUD functions',
        publishedAt: '2018-07-15T14:05:33.000Z',
        thumbnail: 'https://i.ytimg.com/vi/7JejrBPr0iM/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'pI3ILKjIK6Y',
        title: 'TypeScript Groceries API - 05 Item relations',
        publishedAt: '2018-07-17T23:29:01.000Z',
        thumbnail: 'https://i.ytimg.com/vi/pI3ILKjIK6Y/maxresdefault.jpg',
      },
    ],
  },
  {
    title: 'Full Stack MERN Voting App',
    slug: 'full-stack-mern-voting-app',
    pid: 'PLBeQxJQNprbgrNfcntLO8N2Y-dzlMZXZe',
    lastUpdated: '2018-07-11T20:00:00.000Z',
    description:
      'Learn all the parts of the MERN stack (MongoDB, Express, React and Node) as well as Redux by creating a voting application.',
    image: 'mern-vote.jpg',
    tags: ['React', 'MongoDB', 'Redux', 'JavaScript', 'Express'],
    videos: [
      {
        ordinance: 0,
        videoId: '0oziV0FLhXc',
        title: 'Full Stack MERN Voting App - Intro',
        publishedAt: '2018-06-23T04:14:53.000Z',
        thumbnail: 'https://i.ytimg.com/vi/0oziV0FLhXc/maxresdefault.jpg',
      },
      {
        ordinance: 1,
        videoId: '6vZdhqEqEWU',
        title: 'Full Stack MERN Voting App - 01 Setup',
        publishedAt: '2018-06-23T04:43:53.000Z',
        thumbnail: 'https://i.ytimg.com/vi/6vZdhqEqEWU/maxresdefault.jpg',
      },
      {
        ordinance: 2,
        videoId: 'P6pBjD46F8E',
        title: 'Full Stack MERN Voting App - 02 Modularize Express',
        publishedAt: '2018-06-23T18:43:30.000Z',
        thumbnail: 'https://i.ytimg.com/vi/P6pBjD46F8E/maxresdefault.jpg',
      },
      {
        ordinance: 3,
        videoId: 'J6-khGTiR7k',
        title: 'Full Stack MERN Voting App - 03 Connecting to MongoDB',
        publishedAt: '2018-06-23T22:17:10.000Z',
        thumbnail: 'https://i.ytimg.com/vi/J6-khGTiR7k/maxresdefault.jpg',
      },
      {
        ordinance: 4,
        videoId: 'LCa-OlblwSI',
        title: 'Full Stack MERN Voting App - 04 Login and Register',
        publishedAt: '2018-06-26T01:52:21.000Z',
        thumbnail: 'https://i.ytimg.com/vi/LCa-OlblwSI/maxresdefault.jpg',
      },
      {
        ordinance: 5,
        videoId: 'jZt8MbnWyYY',
        title: 'Full Stack MERN Voting App - 05 JSON Web Tokens',
        publishedAt: '2018-06-28T22:57:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/jZt8MbnWyYY/maxresdefault.jpg',
      },
      {
        ordinance: 6,
        videoId: 'EJQfRNz9pEQ',
        title: 'Full Stack MERN Voting App - 06 Starting poll routes',
        publishedAt: '2018-07-01T03:17:26.000Z',
        thumbnail: 'https://i.ytimg.com/vi/EJQfRNz9pEQ/maxresdefault.jpg',
      },
      {
        ordinance: 7,
        videoId: '578bx3HWVQo',
        title: 'Full Stack MERN Voting App - 07 Finishing poll routes',
        publishedAt: '2018-07-01T14:35:36.000Z',
        thumbnail: 'https://i.ytimg.com/vi/578bx3HWVQo/maxresdefault.jpg',
      },
      {
        ordinance: 8,
        videoId: 'RMyDQc_YLhQ',
        title: 'Full Stack MERN Voting App - 08 Setup React client',
        publishedAt: '2018-07-02T23:23:14.000Z',
        thumbnail: 'https://i.ytimg.com/vi/RMyDQc_YLhQ/maxresdefault.jpg',
      },
      {
        ordinance: 9,
        videoId: '4ccVS6bYVdo',
        title: 'Full Stack MERN Voting App - 09 Creating API service',
        publishedAt: '2018-07-03T21:15:27.000Z',
        thumbnail: 'https://i.ytimg.com/vi/4ccVS6bYVdo/maxresdefault.jpg',
      },
      {
        ordinance: 10,
        videoId: 'c6eHO80aidg',
        title: 'Full Stack MERN Voting App - 10 Begin Redux set up',
        publishedAt: '2018-07-04T14:19:47.000Z',
        thumbnail: 'https://i.ytimg.com/vi/c6eHO80aidg/maxresdefault.jpg',
      },
      {
        ordinance: 11,
        videoId: 'N55gAn338bE',
        title: 'Full Stack MERN Voting App - 11 Finish Redux set up',
        publishedAt: '2018-07-04T16:37:41.000Z',
        thumbnail: 'https://i.ytimg.com/vi/N55gAn338bE/maxresdefault.jpg',
      },
      {
        ordinance: 12,
        videoId: 'bM0nLhU6j-Y',
        title: 'Full Stack MERN Voting App - 12 Creating Auth component',
        publishedAt: '2018-07-05T21:55:20.000Z',
        thumbnail: 'https://i.ytimg.com/vi/bM0nLhU6j-Y/maxresdefault.jpg',
      },
      {
        ordinance: 13,
        videoId: 'rMsQbP3QsEw',
        title: 'Full Stack MERN Voting App - 13 Handling errors in React',
        publishedAt: '2018-07-06T20:07:30.000Z',
        thumbnail: 'https://i.ytimg.com/vi/rMsQbP3QsEw/maxresdefault.jpg',
      },
      {
        ordinance: 14,
        videoId: 'HTIy6jQWn2w',
        title: 'Full Stack MERN Voting App - 14 Adding React Router',
        publishedAt: '2018-07-07T05:22:02.000Z',
        thumbnail: 'https://i.ytimg.com/vi/HTIy6jQWn2w/maxresdefault.jpg',
      },
      {
        ordinance: 15,
        videoId: 'YAy7Yh7Aqac',
        title: 'Full Stack MERN Voting App - 15 Application navigation',
        publishedAt: '2018-07-08T18:22:48.000Z',
        thumbnail: 'https://i.ytimg.com/vi/YAy7Yh7Aqac/maxresdefault.jpg',
      },
      {
        ordinance: 16,
        videoId: 'BMAcSVgRV_c',
        title: 'Full Stack MERN Voting App - 16 Adding polls to Redux store',
        publishedAt: '2018-07-08T19:11:34.000Z',
        thumbnail: 'https://i.ytimg.com/vi/BMAcSVgRV_c/maxresdefault.jpg',
      },
      {
        ordinance: 17,
        videoId: 'BPiP6gDYWwg',
        title: 'Full Stack MERN Voting App - 17 Adding polls to front end',
        publishedAt: '2018-07-08T22:06:16.000Z',
        thumbnail: 'https://i.ytimg.com/vi/BPiP6gDYWwg/maxresdefault.jpg',
      },
      {
        ordinance: 18,
        videoId: 'XY-8kL2bQZs',
        title: 'Full Stack MERN Voting App - 18 Handling individual polls',
        publishedAt: '2018-07-09T22:38:17.000Z',
        thumbnail: 'https://i.ytimg.com/vi/XY-8kL2bQZs/maxresdefault.jpg',
      },
      {
        ordinance: 19,
        videoId: 'gHVqqC1bCZU',
        title: 'Full Stack MERN Voting App - 19 Finish application logic',
        publishedAt: '2018-07-10T20:31:16.000Z',
        thumbnail: 'https://i.ytimg.com/vi/gHVqqC1bCZU/maxresdefault.jpg',
      },
      {
        ordinance: 20,
        videoId: '56dtu30fQU8',
        title: 'Full Stack MERN Voting App - 20 Styling',
        publishedAt: '2018-07-11T20:00:00.000Z',
        thumbnail: 'https://i.ytimg.com/vi/56dtu30fQU8/maxresdefault.jpg',
      },
    ],
  },
];
