export const resume = {
  basics: {
    name: 'Kelvin Mai',
    label: 'Software Engineer',
    image: null,
    email: 'kelvin.mai002@gmail.com',
    phone: null,
    url: 'kelvinmai.io',
    summary:
      'Dynamic software engineer with over 5 years of hands-on experience and passionate about functional programming methodologies. Specializing in web technologies including TypeScript, Clojure, React and Golang with a proven track record of delivering robust solutions and adapting to new tools.',
    location: {
      address: null,
      postalCode: null,
      city: 'Las Vegas',
      countryCode: 'US',
      region: 'Nevada',
    },
    profiles: [
      {
        network: 'Youtube',
        url: 'https://youtube.com/c/kelvinmai',
        username: 'kelvinmai',
      },
      {
        network: 'Twitter',
        url: 'https://twitter.com/kelvinmai',
        username: 'kelvinmai',
      },
      {
        network: 'Github',
        url: 'https://github.com/kelvin-mai',
        username: 'kelvinmai',
      },
      {
        network: 'Buy Me A Coffee',
        url: 'https://www.buymeacoffee.com/kelvinmai',
        username: 'kelvinmai',
      },
      {
        network: 'Linkedin',
        url: 'https://www.linkedin.com/in/kelvin-mai-461756152/',
        username: 'Kelvin Mai',
      },
    ],
  },
  work: [
    {
      name: 'Luminare Inc.',
      location: 'Houston, TX',
      locationType: 'Remote',
      description: null,
      skills: ['clojure', 'react', 'postgresql', 'java', 'docker', 'node.js'],
      url: 'https://www.luminare.io/',
      image: 'luminare.png',
      position: 'Software Engineer',
      startDate: '2021-02-08T08:00:00.000Z',
      endDate: '2023-01-20T08:00:00.000Z',
      summary:
        'Rapid development of vaccination management app during the COVID-19 pandemic',
      highlights: [
        'Assisted application migration from node.js to clojure general vaccination software',
        'Development of SMS/Email notifications feature',
        'Optimization and reorganization of data models in PostgreSQL database',
        'Maintained frontend application using Cypress end-to-end testing',
        'Mentored and taught junior developers about Clojure/ClojureScript',
      ],
    },
    {
      name: 'Bonotel Exclusive Travel',
      location: 'Las Vegas, NV',
      locationType: 'Remote',
      description: null,
      skills: [
        'golang',
        'python',
        'java',
        'redis',
        'react',
        'angular',
        'docker',
        'spring boot',
      ],
      url: 'https://www.bonotel.com/',
      image: 'bonotel.png',
      position: 'Software Developer',
      startDate: '2020-07-01T08:00:00.000Z',
      endDate: '2021-02-04T08:00:00.000Z',
      summary:
        'Development of various Travel B2B dependant microservices and internal administration tools.',
      highlights: [
        'Development on both client-facing and administrative frontend applications in both React and Angular',
        'Development and orchestration of Java and Golang microservices',
        'Implemented a Python based ETL worker to update and propagate Redis data',
        'Created SFTP file transfer automation tool in Java as well as a test SFTP server using docker',
      ],
    },
    {
      name: 'Nucamp Coding Bootcamp',
      location: 'Las Vegas, NV',
      locationType: 'Hybrid',
      description: null,
      skills: ['mongodb', 'react native', 'react', 'node.js'],
      url: 'https://www.nucamp.co/',
      image: 'nucamp.png',
      position: 'Bootcamp Instructor',
      startDate: '2020-01-01T08:00:00.000Z',
      endDate: '2020-08-01T08:00:00.000Z',
      summary:
        'Bootcamp instructor responsible for teaching students web development technologies.',
      highlights: [
        'Taught aspiring developers on the MERN stack as well as React Native',
        'Lead classes in person and asynchronously through Zoom meetings',
        'Offer one-on-one tutoring and troubleshooting with web development students',
      ],
    },
    {
      name: 'Vegas.com',
      location: 'Las Vegas, NV',
      locationType: null,
      description: null,
      skills: ['react', 'redux', 'docker', 'node.js', 'react native'],
      url: 'https://www.vegas.com/',
      image: 'vegas.png',
      position: 'Front End Developer',
      startDate: '2019-07-01T07:00:00.000Z',
      endDate: '2020-03-01T08:00:00.000Z',
      summary:
        'Feature development on desktop and mobile retail travel e-commerce web applications.',
      highlights: [
        'Developed and optimized HTML emails using React for purchase confirmations',
        'Implemented mobile cart functionality to use React Router streamlining navigation experience and mobile conversions',
        'Initiated upgrade of React Router from version 2 to 5',
        'Feature development on React Native Windows based kiosk application',
      ],
    },
    {
      name: 'Motivis Learning',
      location: 'Boston, MA',
      locationType: 'Hybrid',
      description: null,
      skills: [
        'react',
        'angular',
        'postgresql',
        'graphql',
        'node.js',
        'typescript',
        'c#',
        'dotnet',
      ],
      url: null,
      image: 'motivis.png',
      position: 'Software Developer',
      startDate: '2018-04-01T07:00:00.000Z',
      endDate: '2019-06-01T07:00:00.000Z',
      summary:
        'R&D and Feature development and maintenance of the cloud-hosted LMS.',
      highlights: [
        'Designed and prototyped GraphQL layer for internal API',
        'Added C# .NET service endpoint to provide full text search using PostgreSQL',
        'Created and maintained internal React data dashboard',
        'Aided conversion of front end applications from Angular 5 to version 6',
        'Aided migration of internal UI components libraries that were compatible with both React and Angular',
      ],
    },
    {
      name: 'DigitalCrafts',
      location: 'Houston, TX',
      locationType: null,
      skills: [
        'javascript',
        'react',
        'mongodb',
        'node.js',
        'python',
        'postgresql',
      ],
      description: null,
      url: 'https://www.digitalcrafts.com/',
      image: 'digitalcrafts.png',
      position: 'Developer Intern',
      startDate: '2018-01-01T08:00:00.000Z',
      endDate: '2018-04-01T07:00:00.000Z',
      summary:
        'Three month paid internship to work with and assist experienced instructors in developing and teach full stack web applications.',
      highlights: [
        'Assist in teaching incoming coding bootcamp students in various web technologies',
        'Offer one-on-one tutoring and troubleshooting with web development students',
        'Worked with experienced instructors to accelerate web development career',
        'Assist in development of internal bootcamp CMS and client-facing bootcamp landing page',
      ],
    },
  ],
  education: [
    {
      institution: 'DigitalCrafts',
      area: 'Full Stack Immersive Bootcamp',
      location: 'Houston, TX',
      startDate: '2017-11-01T07:00:00.000Z',
      endDate: '2018-03-01T08:00:00.000Z',
      studyType: null,
      gpa: null,
      courses: null,
    },
    {
      institution: 'University of California, Riverside',
      area: 'Computer Science Major',
      location: 'Riverside, CA',
      startDate: '2008-09-01T07:00:00.000Z',
      endDate: '2011-02-01T08:00:00.000Z',
      studyType: null,
      gpa: null,
      courses: null,
    },
  ],
};

export type ResumeWork = (typeof resume.work)[0];
// export type Resume {
//   work: ResumeWork[]
// }
