export const yearsSinceStart = () => {
  const pastDate = new Date('2018-04-01T07:00:00.000Z');
  const currentDate = new Date();
  return currentDate.getFullYear() - pastDate.getFullYear();
};

export const resume = {
  basics: {
    name: 'Kelvin Mai',
    label: 'Senior Software Engineer',
    image: null,
    email: 'kelvin.mai002@gmail.com',
    phone: null,
    url: 'kelvinmai.io',
    summary: `Dynamic software engineer with over ${yearsSinceStart()} years of hands-on experience and passionate about functional programming methodologies. Specializing in web technologies including TypeScript, Clojure, React and Golang with a proven track record of delivering robust solutions and adapting to new tools.`,
    location: {
      address: null,
      postalCode: null,
      city: 'Las Vegas',
      countryCode: 'US',
      region: 'Nevada',
    },
    profiles: [
      {
        network: 'Youtube',
        url: 'https://youtube.com/c/kelvinmai',
        username: 'kelvinmai',
      },
      {
        network: 'Github',
        url: 'https://github.com/kelvin-mai',
        username: 'kelvinmai',
      },
      {
        network: 'Buy Me A Coffee',
        url: 'https://www.buymeacoffee.com/kelvinmai',
        username: 'kelvinmai',
      },
      {
        network: 'Linkedin',
        url: 'https://www.linkedin.com/in/kelvin-mai-461756152/',
        username: 'Kelvin Mai',
      },
      {
        network: 'Instagram',
        url: 'https://instagram.com/iamnivlek',
        username: 'iamnivlek',
      },
    ],
  },
  work: [
    {
      name: 'Gravie',
      location: 'Minneapolis, MN',
      locationType: 'Remote',
      description: null,
      skills: [
        'clojure',
        'react',
        'mysql',
        'aws',
        'docker',
        'groovy',
        'grails',
        'redis',
      ],
      url: 'https://www.gravie.com/',
      image: 'gravie.jpg',
      position: 'Senior Software Engineer',
      startDate: '2024-07-15T08:00:00.000Z',
      endDate: '2025-01-01T08:00:00.000Z',
      summary:
        'Development on internal admin tool to aid SFTP automation for insurance clients',
      highlights: [
        'Developed internal admin tools for SFTP file automation by introducing a dry run feature',
        'Enhance the Admin UI for Gravie employees and insurance clients, improving workflow efficiency.',
        'Managed AWS & Redis for file processing in a Groovy on Grails backend.',
        'Mentored Java engineers in React and Clojurescript, facilitating frontend modernization.',
      ],
    },
    {
      name: 'Yieldmos',
      location: 'Mountain View, CA',
      locationType: 'Remote',
      description: null,
      skills: ['typescript', 'react', 'web3', 'nextjs'],
      url: 'https://www.yieldmos.com/',
      image: 'yieldmos.png',
      position: 'Software Consultant',
      startDate: '2023-08-16T08:00:00.000Z',
      endDate: '2024-02-21T08:00:00.000Z',
      summary:
        'Provide development consultation on client facing non-custodial compounding blockchain application',
      highlights: [
        'Collaborated with Rust backend engineers to optimize smart contract interactions.',
        'Development on compounding outpost strategy implementation',
        'Migrated frontend from React 16 to Next.js, enhancing performance and scalability.',
        'Mentored junior developers on React and Typescript best practices.',
      ],
    },
    {
      name: 'Luminare Inc.',
      location: 'Houston, TX',
      locationType: 'Remote',
      description: null,
      skills: ['clojure', 'react', 'postgresql', 'java', 'docker', 'node.js'],
      url: 'https://www.luminare.io/',
      image: 'luminare.png',
      position: 'Software Engineer',
      startDate: '2021-02-08T08:00:00.000Z',
      endDate: '2023-01-20T08:00:00.000Z',
      summary:
        'Rapid development of vaccination management app during the COVID-19 pandemic',
      highlights: [
        'Developed and optimized a COVID-19 vaccination management platform.',
        'Migrated core services from Node.js to Clojure for improved performance and scalability.',
        'Development of SMS/Email notifications feature.',
        'Maintained frontend application using Cypress end-to-end testing.',
        'Mentored and taught junior developers about Clojure/ClojureScript.',
      ],
    },
    {
      name: 'Bonotel Exclusive Travel',
      location: 'Las Vegas, NV',
      locationType: 'Remote',
      description: null,
      skills: [
        'golang',
        'python',
        'java',
        'redis',
        'react',
        'angular',
        'docker',
        'spring boot',
      ],
      url: 'https://www.bonotel.com/',
      image: 'bonotel.png',
      position: 'Software Developer',
      startDate: '2020-03-01T08:00:00.000Z',
      endDate: '2021-02-04T08:00:00.000Z',
      summary:
        'Development of various Travel B2B dependant microservices and internal administration tools.',
      highlights: [
        'Development on both client-facing and administrative frontend applications in both React and Angular',
        'Developed Java and Golang microservices for the Travel B2B platform.',
        'Built a Python-based ETL worker to optimize Redis data propagation.',
        'Automated SFTP file transfers using Java and Docker.',
      ],
    },
    // {
    //   name: 'Nucamp Coding Bootcamp',
    //   location: 'Las Vegas, NV',
    //   locationType: 'Hybrid',
    //   description: null,
    //   skills: ['mongodb', 'react native', 'react', 'node.js'],
    //   url: 'https://www.nucamp.co/',
    //   image: 'nucamp.png',
    //   position: 'Bootcamp Instructor',
    //   startDate: '2020-01-01T08:00:00.000Z',
    //   endDate: '2020-08-01T08:00:00.000Z',
    //   summary:
    //     'Bootcamp instructor responsible for teaching students web development technologies.',
    //   highlights: [
    //     'Taught aspiring developers on the MERN stack as well as React Native',
    //     'Lead classes in person and asynchronously through Zoom meetings',
    //     'Offer one-on-one tutoring and troubleshooting with web development students',
    //   ],
    // },
    {
      name: 'Vegas.com',
      location: 'Las Vegas, NV',
      locationType: null,
      description: null,
      skills: ['react', 'redux', 'docker', 'node.js', 'react native'],
      url: 'https://www.vegas.com/',
      image: 'vegas.png',
      position: 'Front End Developer',
      startDate: '2019-07-01T07:00:00.000Z',
      endDate: '2020-03-01T08:00:00.000Z',
      summary:
        'Feature development on desktop and mobile retail travel e-commerce web applications.',
      highlights: [
        'Implemented React-based HTML email templates for improved purchase confirmation UX.',
        'Implemented mobile cart functionality to use React Router streamlining navigation experience and mobile conversions.',
        'Upgraded React Router (v2 to v5), enhancing navigation performance.',
        'Feature development on React Native Windows based kiosk application.',
      ],
    },
    {
      name: 'Motivis Learning',
      location: 'Boston, MA',
      locationType: 'Hybrid',
      description: null,
      skills: [
        'react',
        'angular',
        'postgresql',
        'graphql',
        'node.js',
        'typescript',
        'c#',
        'dotnet',
      ],
      url: null,
      image: 'motivis.png',
      position: 'Software Developer',
      startDate: '2018-04-01T07:00:00.000Z',
      endDate: '2019-06-01T07:00:00.000Z',
      summary:
        'R&D and Feature development and maintenance of the cloud-hosted LMS.',
      highlights: [
        'Designed and prototyped an internal GraphQL API for better data querying.',
        'Added C# .NET service endpoint to provide full text search using PostgreSQL.',
        'Created and maintained internal React data dashboard.',
        'Led migration from Angular 5 to Angular 6, improving frontend maintainability.',
      ],
    },
    // {
    //   name: 'DigitalCrafts',
    //   location: 'Houston, TX',
    //   locationType: null,
    //   skills: [
    //     'javascript',
    //     'react',
    //     'mongodb',
    //     'node.js',
    //     'python',
    //     'postgresql',
    //   ],
    //   description: null,
    //   url: 'https://www.digitalcrafts.com/',
    //   image: 'digitalcrafts.png',
    //   position: 'Developer Intern',
    //   startDate: '2018-01-01T08:00:00.000Z',
    //   endDate: '2018-04-01T07:00:00.000Z',
    //   summary:
    //     'Three month paid internship to work with and assist experienced instructors in developing and teach full stack web applications.',
    //   highlights: [
    //     'Assist in teaching incoming coding bootcamp students in various web technologies',
    //     'Offer one-on-one tutoring and troubleshooting with web development students',
    //     'Worked with experienced instructors to accelerate web development career',
    //     'Assist in development of internal bootcamp CMS and client-facing bootcamp landing page',
    //   ],
    // },
  ],
  education: [
    {
      institution: 'DigitalCrafts',
      area: 'Full Stack Immersive Bootcamp',
      location: 'Houston, TX',
      startDate: '2017-11-01T07:00:00.000Z',
      endDate: '2018-03-01T08:00:00.000Z',
      studyType: null,
      gpa: null,
      courses: null,
    },
    {
      institution: 'University of California, Riverside',
      area: 'Computer Science Major',
      location: 'Riverside, CA',
      startDate: '2008-09-01T07:00:00.000Z',
      endDate: '2011-02-01T08:00:00.000Z',
      studyType: null,
      gpa: null,
      courses: null,
    },
  ],
  skills: [
    {
      name: 'Programming Languages',
      keywords: [
        'TypeScript',
        'JavaScript',
        'Clojure',
        'ClojureScript',
        'Golang (Go)',
        'Java',
        'Groovy',
        'Python',
        'C#',
        'HTML & CSS',
      ],
    },
    {
      name: 'Frontend Technologies',
      keywords: [
        'React',
        'React Native',
        'React Router',
        'Redux',
        'Next.js',
        'Angular',
        'Bootstrap',
        'Material UI',
        'Tailwind CSS',
        'Cypress',
        'Jest',
      ],
    },
    {
      name: 'Backend & Databases',
      keywords: [
        'Node.js',
        'Express.js',
        'ASP.NET Core',
        'Spring Boot',
        'Rest APIs',
        'GraphQL',
        'PostgreSQL',
        'MySQL',
        'MongoDB',
        'Web3',
      ],
    },
    {
      name: 'DevOps & Tools',
      keywords: [
        'Docker',
        'Kubernetes',
        'AWS (Amazon Web Services)',
        'GCP (Google Cloud Platform)',
        'Microsoft Azure',
        'RabbitMQ',
        'Jenkins',
        'CI/CD',
        'Github Actions',
        'Git',
        'Redis',
        'Linux',
      ],
    },
  ],
  projects: [
    {
      name: 'Youtube Channel',
      url: 'https://youtube.com/@kelvinmai',
      startDate: '2017-06-21',
      endDate: null,
      description:
        'Tutorial and course content creation about web development and software engineering topics.',
      highlights: [
        'Grew an audience of over 7,000 subscribers on YouTube.',
        'Developed project-based learning resources to simplify complex programming concepts.',
      ],
    },
    {
      name: 'Daggerheart Brews',
      url: 'https://www.daggerheartbrews.com/',
      startDate: '2024-03-22',
      endDate: null,
      description:
        'Daggerheart TTRPG fan applicaiton for generating homebrew cards for gameplay.',
      highlights: [],
    },
  ],
};

export type Resume = typeof resume;
