/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "color-picker": {
    name: "color-picker",
    title: "Color Picker",
    description: "A color picker component",
    type: "registry:component",
    files: [{
      path: "src/registry/default/ui/color-picker.tsx",
      type: "registry:component",
    }],
  },
  "theme-switch": {
    name: "theme-switch",
    title: "Theme Switch",
    description: "Animated theme switch",
    type: "registry:component",
    files: [{
      path: "src/registry/default/ui/theme-switch.tsx",
      type: "registry:component",
    }],
  },
  "theme-switch-demo": {
    name: "theme-switch-demo",
    title: "",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/default/examples/theme-switch-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/default/examples/theme-switch-demo.tsx")),
    source: `import { ThemeSwitch } from '@/registry/default/ui/theme-switch';

export default function ThemeSwitchDemo() {
  return <ThemeSwitch />;
}
`
  },
}